import Head from 'next/head';

import styles from '@/styles/Home.module.css';
import SwipeCards from '@/pages/SwipeCards';
import { Montserrat } from '@next/font/google';
import { Web3Button } from '@web3modal/react';

const montserrat = Montserrat({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Gather</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.main} ${montserrat.className}`}>
        <Web3Button />
        <SwipeCards />
      </main>
    </>
  );
}
